language: python

addons:
  postgresql: "9.3"

install:
  - pip install pylint
  - npm install -g bower
  - sudo apt-get update && sudo apt-get install -y python-numpy python-scipy python-psycopg2

script:
  - pylint nutsurv --disable=all --enable=E0602
  - pip install -r requirements/production.txt
  - pip install -r requirements/development.txt
  - psql -f enable_postgis.sql -U postgres
  - psql -f make_nutsurv_dev.sql -U postgres
  - bower install
  - mkdir nutsurv/components
  - mv bower_components nutsurv/components
  - cat configuration.py-default | sed s/postgres/nutsurv_dev/ > configuration.py
  - echo 'POSTGIS_VERSION = (2, 1)' >> configuration.py
  - ./manage.py test

